authors:
  Lilon:
    name: Margin writer
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/87666705?s=400&v=4
    url: https://technical-margins.github.io/material-margins/en/about/
