authors:
  Lilon:
    name: Margin writer
    description: Créatrice
    avatar: https://avatars.githubusercontent.com/u/87666705?s=400&v=4
    url: https://technical-margins.github.io/material-margins/fr/about/