FROM squidfunk/mkdocs-material:9.5.44

# Install additional plugins
RUN apk add --no-cache python3 py3-pip && \
    pip install mkdocs-glightbox==0.3.7 mkdocs-static-i18n==1.2.0 mkdocs-macros-plugin==1.0.5

# Set the working directory
WORKDIR /docs
