FROM squidfunk/mkdocs-material

# Install necessary plugins using pip
RUN apk add --no-cache python3 py3-pip && \
    pip install mkdocs-macros-plugin mkdocs-glightbox mkdocs-static-i18n openai deepl tiktoken

# Set the working directory to /docs
WORKDIR /docs
