################ Project Information ################

site_name: 'Technical Margins'
site_author: The Margin Writer

################ Misc configuration ################
use_directory_urls: true                  # Use directory URLs instead of file URLs.

################ Logs (mkdocs serve or build) ################
validation:
  nav:
    omitted_files: info       # Warn about omitted files in the nav.
    not_found: warn           # Warn about files in the nav that cannot be found.
    absolute_links: info      # Warn about absolute links in the nav.
  links:
    not_found: warn           # Warn about links in the content that cannot be found.
    anchors: info             # Warn about anchors in the content that cannot be found.
    absolute_links: info      # Warn about absolute links in the content.
    unrecognized_links: info  # Warn about unrecognized links in the content.

################ Theme Configuration ################
theme:
    name: material
    favicon: assets/images/favicon.ico
    custom_dir: '../../overrides/'
    palette:
        - scheme: margin
          primary: custom
          accent: custom
          toggle:
            icon: material/weather-night
            name: Dark mode | Mode sombre
        - scheme: slate
          primary: custom
          accent: custom
          toggle:
            icon: material/weather-hazy
            name: Light mode | Mode clair
    font:
        text: Nunito
        code: Roboto Mono
    icon:
      logo: fontawesome/solid/pen-nib
      menu: material/microsoft-xbox-controller-menu
      previous: material/skip-previous-outline
      next: material/skip-next-outline
      alternate: material/translate-variant
      admonition:
        example: material/tooltip-edit-outline
        note: material/pin-outline
        abstract: material/eye-outline
        info: material/information-outline
        tip: material/star-circle-outline
        success: material/check-circle-outline
        question: material/help-circle-outline
        warning: material/alert-circle-outline
        failure: material/close-circle-outline
        danger: material/radioactive-circle-outline
        bug: material/bell-circle-outline
        quote: material/comma-circle-outline
    features:
        - navigation.footer         # Footer navigation.
        - navigation.indexes        # Index pages for each section.
        - navigation.sections       # Section navigation.
        - navigation.tabs           # Tab navigation at the top of the page.
#        - navigation.tabs.sticky   # Retain the tab navigation at the top of the page while scrolling.
        - navigation.top            # Add a "Back to top" button.
        - toc.follow                # Follow navigation in the TOC
#        - toc.integrate            # Uncomment to integrate right-side TOC into the left panel.

################ Extra Configuration ################
extra_css:
  - assets/stylesheets/extra.css 

extra_javascript:
  - assets/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra:
  analytics:
    provider: google
    property: G-9QESW2GJNK
  social:
#    - icon: fontawesome/brands/linkedin
#      link: https://www.linkedin.com/in/.../
    - icon: material/github
      link: https://github.com/technical-margins
    - icon: material/send-circle-outline
      link: mailto:themarginwriter@outlook.com
  alternate:
    - name: English
      link: /material-margins/en/
      lang: en
    - name: Français
      link: /material-margins/fr/
      lang: fr
    - name: 中文
      link: /material-margins/zh/
      lang: zh
# Macros to be used in the markdown files, format {{ macro.name }}.
  author:
    name: Lise
  blog:
    name: Technical Margins
  generator: true                        # Add a generator name and link to the footer.


################ Markdown Extensions ################
markdown_extensions:
  - admonition            
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:    # Insert markdown or HTML snippets into other markdown files.
      base_path: [docs/assets/snippets]
      check_paths: true
  - attr_list             # Allow attributes to your markdown elements.
  - md_in_html            # Allow markdown inside HTML blocks.
  - pymdownx.emoji:       # Emoji support.
      emoji_index: !!python/name:material.extensions.emoji.twemoji      # Use Twemoji.
      emoji_generator: !!python/name:material.extensions.emoji.to_svg   # Generate SVGs.
      options:
        custom_icons:
          - '../../overrides/.icons/'
  - pymdownx.tabbed:      # Create tabbed content.
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true       # Use generic TeX delimiters.

################ Plugins ################
plugins:
  - blog:
      enabled: true
      blog_toc: true
      post_date_format: full
      categories_toc: true
  - tags:
      enabled: true
      tags: true
  - search:
      enabled: true                                         
      pipeline:
#          - stemmer  # Search for the root of words. Somehow cannot search for full words.
          - lower    # Lowercase all words.
          - strip    # Remove punctuation.
          - searchIndex
          - stopWordFilter # Remove common words from search.
          - trimmer   # Remove leading and trailing whitespace.
      separator: '[\s\-,:!=\[\]()"/]+\.(?!\d)&[lg]t;' # Characters used to split words.
  - glightbox:
       touchNavigation: true
       loop: false    # Disable the loop.
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
  - macros
