INHERIT: ../mkdocs.yml    # Inherit the configuration from the parent file

################ Project information ################
docs_dir: '../../docs/en/'
site_dir: '../../generated/en/'
site_description: >-
  Technical Margins is a space for exploring the overlooked edges of technical writing. For technical writers and curious minds, this blog dives into the hidden layers of documentation, random reflections, and the art of sharing diverse information.

################ Language configuration ################
theme:
  language: en

plugins:
  - blog:
      archive_date_format: yyyy-MM
      archive_url_date_format: yyyy/MM
      categories_allowed:
        - Random Thoughts
        - Technical Writing
        - AI
  - tags:
      tags_file: blog/tags.md
  - search:                                         
      lang: en

################ Analytics feedback localisation ################
extra:
  analytics: 
    feedback:
      title: What are your thoughts on this?
      ratings:
        - icon: material/thumb-up-outline
          name: This piece inspired me
          data: 1
          note: >-
            Thanks for your feedback
        - icon: material/thumb-down-outline
          name: I see things differently
          data: 0
          note: >- 
            Thanks for your feedback

################ Nagivation ################
nav:
  - Home:
    - index.md
  - Blog:
    - blog/index.md
    - Tags: blog/tags.md
  - About:
    - about/index.md